### PR TITLE
fix broken pool option overwrite via CLI

### LINKED ISSUE #340: Config file override by command line possible?
Hello.

Running under Ubuntu 16.04 LTS. This miner is the first one I've come across that cannot run w/o a config.txt file.  Other miners use config files too, but they are not mandatory. I usually add rig name after wallet address like $WALLET.$RIG with RIG set to (hostname). This parameter is passed via command line and it works with other miners.

But XMRSTAK picks up parameters from the config.txt once it has been created and it **ignores** newer params passed via command line (contrary to what -h command claims). I could erase the config.txt on every run, however, XMRSTAK enters a kind of interactive state when it asks questions about coin name and pool parameters. 

So, if I had, say, 100 rigs, I would have to run XMRSTAK a 100 times to create an individual config file for every rig.

p.s. I just realized your group name is FIRE ICE-UK. If written as one word, it reads "fierce-uk".

### PR DESCRIPTION
**Pull request by psychocrypt**
fix #340

With #90 the option to overwrite the pool settings via CLI options is broken.

This pull request will allow to overwrite the options of the pool with the highest weighting.

### CODE REVIEW

File: xmrstak/cli/cli-miner.cpp [hunk 1]
```diff
@@ -82,7 +82,7 @@ void help()
 	cout<<"  --nvidia FILE         NVIDIA backend miner config file"<<endl;
 #endif
 	cout<<" "<<endl;
-	cout<<"The Following options temporary overwrites the config file settings:"<<endl;
+	cout<<"The Following options temporary overwrites the config entries of \nthe pool with the highest weighting:"<<endl;
```
Comment (fireice-uk) [inline xmrstak/cli/cli-miner.cpp]: Sp. `weight` not `weighting`

**Comment by psychocrypt** [comment]
@fireice-uk done
