### PR TITLE
fix job consume

### LINKED ISSUE #1505: Xmr-Stak2.4.3 continues mining "rejected shares" for hours after reconnecting to pool
Please provide as much as possible information to reproduce the issue.

# Basic information
V2.4.3 will run for a decent amount of time (days)  w/o any issues..... 100% accepted share rate... then immediately following an internet caused loss of connection to pool the v2.4.3 will attempt to reconnect to pool.  The reconnection appears in the log.txt as normal except ALL following shares are now "rejected shares".  The miner is NOT banned and there were NO duplicate shares nor bad shares submitted prior to the disconnection from pool (actually up to 100% accepted prior to disconnection).  It seems the reconnect is not complete as the pool shows NO shares submitted during this time.  Unfortunately, the miner continues mining the "rejected shares" for hours...... until time that it is manually turned off and restarted.
connection rejection

Intel Pentium G3250 3.2GHz   - Type of the CPU.  
Sapphire Nitro rx580 x6  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use? Windows 10 1079
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```yes...................
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.11

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"

cd /

cd xmr-stak-2.4.3

mkdir build

cd build

set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl;

cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..

cmake --build . --config Release --target install


    85 Warning(s)
    0 Error(s)
   Time Elapsed 00:13:00.89

cd bin\Release

copy C:\xmr-stak-dep\openssl\bin\* .


 


 run `./xmr-stak --version-long` and add the output here
  ```C:\xmr-stak-2.4.3_\build\bin\Release_x64>xmr-stak --version-long
Version: xmr-stak/2.4.3/26a5d65f/unknown/win/nvidia-amd-cpu/aeon-cryptonight-monero/0
Press any key to exit.

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

### PR DESCRIPTION
**Pull request by psychocrypt**
~~fix #1505~~
~~fix or reduce #1337 #1222~~

- remove switch_work in all classes `minethd`
- move `consume_work` into `globalStates`
- remove the limit that each worker thread must be consume a job before we can receive a new job. 
- miner should not freeze if one GPU is hanging

In the previous implementation it was possible that a worker thread consumed and already old job if the pool is sending jobs faster than a batch of nonces is calculated. The reson is that the current implementation force that each worker must consume the oldest job in the queue before a new job can be added. On a GPU the time to process a job (a batch of nonces) before checking again if the job has changed much longer than on a CPU. A GPU needs typical ~1 sec+ (slow GPUs sometimes 10sec).

example of the PR behavior if the job is faster changed than processed:

- 1. job switch
- 2. thread consume
- 3. job switch 
- 4. job switch again
- 5. thread is finishing II. and never consume III

# Test

- [x] CPU
- [x] AMD
- [x] NVIDIA

[update:] I thought there is a race condition and deadlock in the code I changes. After discussions with @fireice-uk it looks like I was wrong. Therefore I updated the PR description.

### CODE REVIEW

**Comment by fireice-uk** [comment]
This isn't correct. Consume needs to be per thread. Please explain in numbered steps how you think a deadlock can happen.

**Comment by fireice-uk** [comment]
Also please note that a deadlock in worker threads wouldn't affect the network thread. I see some people already think it is some kind of client-side fix for nicehash having shitty software.

With regards to nicehash, I think we should silence them like cast-xmr but make it optional wit default to false.

File: THIRD-PARTY-LICENSES [hunk 1]
```diff
@@ -5,7 +5,7 @@ This application bundles the following third-party software in accordance with t
 Package: Original NVidia mining code
 Authors: tsiv and KlausT
 License: GNU GPLv3
-Notes: Improvements are (c) of Xmr-Stak team
+Notes: Improvements are (c) of Xmr-Stak team team and are covered by GNU GPLv3
```
Comment (fireice-uk) [inline THIRD-PARTY-LICENSES]: > team team

File: THIRD-PARTY-LICENSES [hunk 2]
```diff
@@ -27,3 +27,10 @@ Authors: okdshin
 License: MIT License
 
 -------------------------------------------------------------------------
+
+Package: cpputil
+Authors: Will Zhang
+Source: https://github.com/willzhang4a58/cpputil
```
Comment (fireice-uk) [inline THIRD-PARTY-LICENSES]: Nice to see. Big thanks for dealing with licensing and big thanks to @willzhang4a58 for the code.

File: xmrstak/cpputil/read_write_lock.h [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+ * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+ * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+ * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+ * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+ * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+ * SOFTWARE.
+ */
+
+#ifndef CPPUTIL_READ_WRITE_LOCK_H_
+#define CPPUTIL_READ_WRITE_LOCK_H_
```
Comment (fireice-uk) [inline xmrstak/cpputil/read_write_lock.h]: Can we get this to the standard stak format -> tab indent and `#pragma once`

File: xmrstak/backend/globalStates.cpp [hunk 4]
```diff
@@ -33,24 +33,36 @@
...
-	// iConsumeCnt is a basic lock-like polling mechanism just in case we happen to push work
-	// faster than threads can consume them. This should never happen in real life.
-	// Pool cant physically send jobs faster than every 250ms or so due to net latency.
-
-	while (iConsumeCnt.load(std::memory_order_seq_cst) < iThreadCount)
-		std::this_thread::sleep_for(std::chrono::milliseconds(100));
+	jobLock.WriteLock();
+	
+	// this notifies all threads that the job has changed
+	iGlobalJobNo++;
```
Comment (fireice-uk) [inline xmrstak/backend/globalStates.cpp]: This is in a wrong place. The order that I told you:

when a global job is being written you:
acquire write lock

write the job
release the lock
increase the jobno

when a thread gets a job:
acquire read lock
copy the job
set the job no to global (!!! note the difference with write lock)
release read lock

Is slightly more efficient since the threads only start to read when the resource is available

**Comment by psychocrypt** [comment]
updated

**Comment by fireice-uk** [comment]
Needs a rebase before testing

**Comment by psychocrypt** [comment]
I removed the BUG label. The point that all worker must consume a job before a new job can be added for the worker is no real bug. A drawback of this restriction can be that the miner is mining old jobs even if newer jobs are received but I do not know if this can be defined as BUG.
